// ============================================================
// MATCHING ENGINE TESTS: Validate the core matching logic
// ============================================================
// These tests verify the most critical behavior of the exchange:
// that orders match correctly at the right prices with the right
// quantities. Getting matching wrong = financial losses.
//
// At real exchanges, the matching engine test suite has thousands
// of test cases covering every edge case. We cover the essentials.
// ============================================================

#include <gtest/gtest.h>
#include "core/MatchingEngine.h"

using namespace exchange;

class MatchingEngineTest : public ::testing::Test {
protected:
    MatchingEngine engine;
    std::vector<Trade> trades;

    void SetUp() override {
        // Capture all trades generated by the engine.
        // This lets us verify exactly what matched.
        engine.set_trade_callback([this](const Trade& t) {
            trades.push_back(t);
        });
    }
};

// ---- Basic Matching ----

TEST_F(MatchingEngineTest, NoMatchWhenBookIsEmpty) {
    // Submit a limit buy, nothing to match against
    engine.submit_order("AAPL", Side::Buy, OrderType::Limit, 100.00, 50);

    EXPECT_EQ(trades.size(), 0);
    EXPECT_EQ(engine.get_order_book("AAPL").order_count(), 1);
}

TEST_F(MatchingEngineTest, ExactPriceMatch) {
    // Sell at $100, then buy at $100 → should match
    engine.submit_order("AAPL", Side::Sell, OrderType::Limit, 100.00, 50);
    engine.submit_order("AAPL", Side::Buy, OrderType::Limit, 100.00, 50);

    ASSERT_EQ(trades.size(), 1);
    EXPECT_DOUBLE_EQ(trades[0].price, 100.00);
    EXPECT_EQ(trades[0].quantity, 50);

    // Both orders should be fully filled → book is empty
    EXPECT_EQ(engine.get_order_book("AAPL").order_count(), 0);
}

TEST_F(MatchingEngineTest, BuyerGetsPriceImprovement) {
    // Sell at $99 (cheap seller). Buy at $101 (willing to pay more).
    // Trade should happen at $99 (the resting sell price).
    // The buyer "saved" $2/share, this is price improvement.
    engine.submit_order("AAPL", Side::Sell, OrderType::Limit, 99.00, 50);
    engine.submit_order("AAPL", Side::Buy, OrderType::Limit, 101.00, 50);

    ASSERT_EQ(trades.size(), 1);
    EXPECT_DOUBLE_EQ(trades[0].price, 99.00);  // Resting order's price
}

TEST_F(MatchingEngineTest, PartialFill) {
    // Sell 100 shares, but only buy 30 → partial fill
    engine.submit_order("AAPL", Side::Sell, OrderType::Limit, 100.00, 100);
    engine.submit_order("AAPL", Side::Buy, OrderType::Limit, 100.00, 30);

    ASSERT_EQ(trades.size(), 1);
    EXPECT_EQ(trades[0].quantity, 30);

    // Sell order still has 70 shares resting on the book
    auto& book = engine.get_order_book("AAPL");
    EXPECT_EQ(book.order_count(), 1);
    EXPECT_EQ(book.total_ask_quantity(), 70);
}

TEST_F(MatchingEngineTest, SweepMultiplePriceLevels) {
    // Three sellers at different prices
    engine.submit_order("AAPL", Side::Sell, OrderType::Limit, 100.00, 30);
    engine.submit_order("AAPL", Side::Sell, OrderType::Limit, 101.00, 30);
    engine.submit_order("AAPL", Side::Sell, OrderType::Limit, 102.00, 30);

    // Big buy order that sweeps through all three levels
    engine.submit_order("AAPL", Side::Buy, OrderType::Limit, 102.00, 80);

    // Should generate 3 trades at increasing prices
    ASSERT_EQ(trades.size(), 3);
    EXPECT_DOUBLE_EQ(trades[0].price, 100.00);  // Best ask first
    EXPECT_EQ(trades[0].quantity, 30);
    EXPECT_DOUBLE_EQ(trades[1].price, 101.00);
    EXPECT_EQ(trades[1].quantity, 30);
    EXPECT_DOUBLE_EQ(trades[2].price, 102.00);
    EXPECT_EQ(trades[2].quantity, 20);           // Only 20 left of the 80

    // 10 shares left at $102 on the ask side
    EXPECT_EQ(engine.get_order_book("AAPL").total_ask_quantity(), 10);
}

// ---- Time Priority ----

TEST_F(MatchingEngineTest, TimePriorityAtSamePrice) {
    // Two sells at the same price, first one should match first
    OrderId first = engine.submit_order("AAPL", Side::Sell, OrderType::Limit, 100.00, 50);
    OrderId second = engine.submit_order("AAPL", Side::Sell, OrderType::Limit, 100.00, 50);

    // Buy 50, should match against 'first' (arrived earlier)
    engine.submit_order("AAPL", Side::Buy, OrderType::Limit, 100.00, 50);

    ASSERT_EQ(trades.size(), 1);
    EXPECT_EQ(trades[0].sell_order_id, first);   // First order matched
    EXPECT_EQ(engine.get_order_book("AAPL").order_count(), 1);  // Second still resting
}

// ---- Market Orders ----

TEST_F(MatchingEngineTest, MarketBuyFillsImmediately) {
    engine.submit_order("AAPL", Side::Sell, OrderType::Limit, 100.00, 50);

    // Market buy, should fill immediately at best ask ($100)
    engine.submit_order("AAPL", Side::Buy, OrderType::Market, 0.0, 30);

    ASSERT_EQ(trades.size(), 1);
    EXPECT_DOUBLE_EQ(trades[0].price, 100.00);
    EXPECT_EQ(trades[0].quantity, 30);
}

TEST_F(MatchingEngineTest, MarketOrderCancelledWhenNoLiquidity) {
    // Market buy with empty book, should be rejected/cancelled, not resting
    engine.submit_order("AAPL", Side::Buy, OrderType::Market, 0.0, 50);

    EXPECT_EQ(trades.size(), 0);
    EXPECT_EQ(engine.get_order_book("AAPL").order_count(), 0);  // Not on book
}

// ---- IOC Orders ----

TEST_F(MatchingEngineTest, IOCFillsAndCancelsRemainder) {
    engine.submit_order("AAPL", Side::Sell, OrderType::Limit, 100.00, 30);

    // IOC buy 50, should fill 30 (all available) and cancel remaining 20
    engine.submit_order("AAPL", Side::Buy, OrderType::IOC, 100.00, 50);

    ASSERT_EQ(trades.size(), 1);
    EXPECT_EQ(trades[0].quantity, 30);

    // IOC remainder cancelled, book should be empty
    EXPECT_EQ(engine.get_order_book("AAPL").order_count(), 0);
}

// ---- Cancel ----

TEST_F(MatchingEngineTest, CancelPreventsMatch) {
    OrderId sell_id = engine.submit_order("AAPL", Side::Sell, OrderType::Limit, 100.00, 50);

    // Cancel the sell before a buy comes in
    EXPECT_TRUE(engine.cancel_order("AAPL", sell_id));

    // Now submit a buy at the same price, no match possible
    engine.submit_order("AAPL", Side::Buy, OrderType::Limit, 100.00, 50);

    EXPECT_EQ(trades.size(), 0);
}

// ---- Validation ----

TEST_F(MatchingEngineTest, RejectsZeroQuantity) {
    OrderId id = engine.submit_order("AAPL", Side::Buy, OrderType::Limit, 100.00, 0);
    EXPECT_EQ(id, 0);  // 0 = rejected
    EXPECT_EQ(engine.stats().total_rejects, 1);
}

TEST_F(MatchingEngineTest, RejectsNegativePriceLimit) {
    OrderId id = engine.submit_order("AAPL", Side::Buy, OrderType::Limit, -5.00, 100);
    EXPECT_EQ(id, 0);
    EXPECT_EQ(engine.stats().total_rejects, 1);
}

// ---- Multi-Symbol ----

TEST_F(MatchingEngineTest, DifferentSymbolsDontMatch) {
    engine.submit_order("AAPL", Side::Sell, OrderType::Limit, 100.00, 50);
    engine.submit_order("GOOG", Side::Buy, OrderType::Limit, 100.00, 50);

    // Different symbols, should NOT match
    EXPECT_EQ(trades.size(), 0);
    EXPECT_EQ(engine.get_order_book("AAPL").order_count(), 1);
    EXPECT_EQ(engine.get_order_book("GOOG").order_count(), 1);
}

// ---- Statistics ----

TEST_F(MatchingEngineTest, StatsTracking) {
    engine.submit_order("AAPL", Side::Sell, OrderType::Limit, 100.00, 50);
    engine.submit_order("AAPL", Side::Buy, OrderType::Limit, 100.00, 50);

    EXPECT_EQ(engine.stats().total_orders, 2);
    EXPECT_EQ(engine.stats().total_trades, 1);
    EXPECT_EQ(engine.stats().total_volume, 50);
    EXPECT_NEAR(engine.stats().total_notional, 5000.00, 0.01);
    EXPECT_GT(engine.stats().avg_latency_ns(), 0);
}
